'use client';
import {useState} from 'react';
type Row={name:string;phone:string;area?:string;address?:string;usualQuantity?:number;frequencyDays?:number};
function csv(text:string):string[][]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(ch===','&&!quoted){row.push(cell);cell='';}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell='';}else cell+=ch;}row.push(cell);if(row.some(x=>x.trim()))rows.push(row);return rows;}
async function xlsx(file:File):Promise<string[][]>{
 const buffer=await file.arrayBuffer(),bytes=new Uint8Array(buffer),v=new DataView(buffer),entries=new Map<string,{offset:number;size:number;method:number;raw:number}>();let end=bytes.length-22;
 while(end>=Math.max(0,bytes.length-65557)&&v.getUint32(end,true)!==0x06054b50)end--;if(end<0)throw Error('Invalid Excel file.');
 let p=v.getUint32(end+16,true);for(let i=0;i<v.getUint16(end+10,true);i++){if(v.getUint32(p,true)!==0x02014b50)throw Error('Invalid Excel archive.');const length=v.getUint16(p+28,true),extra=v.getUint16(p+30,true),comment=v.getUint16(p+32,true);const name=new TextDecoder().decode(bytes.slice(p+46,p+46+length));entries.set(name,{offset:v.getUint32(p+42,true),size:v.getUint32(p+20,true),raw:v.getUint32(p+24,true),method:v.getUint16(p+10,true)});p+=46+length+extra+comment;}
 async function xml(name:string){const e=entries.get(name);if(!e)return null;if(e.raw>5000000)throw Error('Spreadsheet too large. Use up to 200 rows.');const start=e.offset+30+v.getUint16(e.offset+26,true)+v.getUint16(e.offset+28,true);const data=bytes.slice(start,start+e.size);let text:string;if(e.method===0)text=new TextDecoder().decode(data);else if(e.method===8)text=await new Response(new Blob([data]).stream().pipeThrough(new DecompressionStream('deflate-raw'))).text();else throw Error('Save this file as .xlsx or CSV.');return new DOMParser().parseFromString(text,'application/xml');}
 const shared=await xml('xl/sharedStrings.xml'),strings=shared?Array.from(shared.getElementsByTagName('si')).map(n=>Array.from(n.getElementsByTagName('t')).map(x=>x.textContent??'').join('')):[];
 const book=await xml('xl/workbook.xml'),rels=await xml('xl/_rels/workbook.xml.rels'),id=book?.getElementsByTagName('sheet')[0]?.getAttribute('r:id');const target=Array.from(rels?.getElementsByTagName('Relationship')??[]).find(x=>x.getAttribute('Id')===id)?.getAttribute('Target');const path=target?(target.startsWith('/')?target.slice(1):'xl/'+target.replace(/^\.\//,'')):'xl/worksheets/sheet1.xml';
 const sheet=await xml(path);if(!sheet)throw Error('No worksheet found.');return Array.from(sheet.getElementsByTagName('row')).slice(0,202).map(row=>{const cells:string[]=[];for(const c of Array.from(row.getElementsByTagName('c'))){const letters=(c.getAttribute('r')??'A').replace(/\d/g,'');let index=0;for(const letter of letters)index=index*26+letter.charCodeAt(0)-64;const value=c.getElementsByTagName('v')[0]?.textContent??'';cells[index-1]=c.getAttribute('t')==='s'?strings[Number(value)]??'':c.getAttribute('t')==='inlineStr'?c.textContent??'':value;}return cells;});
}
export default function CustomerImport({onClose,onDone}:{onClose:()=>void;onDone:(message:string)=>Promise<void>}){
 const [rows,setRows]=useState<Row[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState('');
 async function load(file?:File){if(!file)return;setError('');setResult('');try{if(file.size>2000000)throw Error('Choose a file smaller than 2 MB.');const data=file.name.toLowerCase().endsWith('.xlsx')?await xlsx(file):csv(await file.text());const headers=data[0]?.map(x=>(x??'').replace(/^\uFEFF/,'').trim().toLowerCase().replace(/[ _-]/g,''))??[];const idx=(...names:string[])=>headers.findIndex(h=>names.includes(h));const phone=idx('phone','mobile','mobilenumber','phonenumber');if(phone<0)throw Error('Include a Phone or Mobile column.');if(data.length>201)throw Error('Import up to 200 customers at a time.');setRows(data.slice(1).filter(r=>r.some(Boolean)).map(r=>({phone:r[phone]??'',name:r[idx('name','customer','customername')]??'',area:r[idx('area')]??'',address:r[idx('address')]??'',usualQuantity:Number(r[idx('usualcans','cans','usualquantity')]||2),frequencyDays:Number(r[idx('frequencydays','frequency')]||7)})));}catch(e){setError((e as Error).message);setRows([]);}}
 async function contacts(){setError('');try{const picker=(navigator as Navigator&{contacts?:{select:(fields:string[],options:{multiple:boolean})=>Promise<{name?:string[];tel?:string[]}[]>}}).contacts;if(!picker)throw Error('Contact import is available in supported Android browsers. You can use Excel or CSV instead.');const selected=await picker.select(['name','tel'],{multiple:true});if(selected.length>200)throw Error('Choose up to 200 contacts.');setRows(selected.map(c=>({name:c.name?.[0]??'',phone:c.tel?.[0]??''})));}catch(e){if((e as Error).name!=='AbortError')setError((e as Error).message);}}
 async function save(){setBusy(true);setError('');try{const response=await fetch('/api/commercial/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customers:rows})});const body=await response.json() as {error?:string;imported:number;invalid:number;skipped:number};if(!response.ok)throw Error(body.error);const message=`${body.imported} imported · ${body.skipped} existing/duplicate · ${body.invalid} invalid`;setResult(message);setRows([]);await onDone(message);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="gc-overlay" onClick={onClose}><section className="gc-dialog gc-import-dialog" role="dialog" aria-modal="true" aria-label="Import customers" onClick={e=>e.stopPropagation()}><button className="gc-close" onClick={onClose} aria-label="Close">×</button><h2>Import customers</h2><p>Choose contacts or an Excel (.xlsx) / CSV file. Up to 200 at a time. Existing customers stay unchanged.</p><button className="gc-primary" onClick={()=>void contacts()}>Choose phone contacts</button><label>Excel or CSV<input type="file" accept=".xlsx,.csv" onChange={e=>void load(e.target.files?.[0])}/></label><a href="/customer-import-template.csv" download>Download sample spreadsheet</a>{rows.length>0&&<><p>{rows.length} customers ready to check</p><div className="gc-import-preview">{rows.map((r,i)=><div key={i}><strong>{r.name||'New customer'}</strong><small>{r.phone} · {r.area||'No area'}</small><button onClick={()=>setRows(x=>x.filter((_,j)=>i!==j))} aria-label={`Remove ${r.name||r.phone}`}>×</button></div>)}</div></>}{error&&<p role="alert" className="quick-error">{error}</p>}{result&&<p role="status">{result}</p>}<button className="gc-primary" disabled={busy||!rows.length} onClick={()=>void save()}>{busy?'Importing…':`Import ${rows.length} customers`}</button></section></div>;
}
