'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import CustomerImport from '@/components/customer-import';
import InstallApp from '@/components/install-app';
import QuickOrder from '@/components/quick-order';
import { tx } from '@/components/labels';
import { ArrowRight, Check, Copy, Droplets, LogOut, Minus, Plus, RefreshCw, Truck, Users, Wallet, Settings2, Phone, ClipboardList, Search, Home } from 'lucide-react';

type Customer = { id: number; name: string; phone: string; address: string; area: string; usual_quantity: number; frequency_days: number; last_delivered_at: string | null };
type Order = { id: number; customer_id: number; customer: string; quantity: number; status: string; price_cents: number; returned_cans: number; route_rank: number; phone: string; address: string; area: string };
type Payment = { id: number; customer_id: number; amount_cents: number };
type Account={customer_id:number;balance_cents:number;cans_out:number};
type Summary={day:string;sales_cents:number;collected_cents:number;delivered_cans:number;returned_cans:number;dues_cents:number;credit_cents:number;cans_out:number};
type Billing = { trialEnd?: string | null; status: string; checkoutUrl: string | null; currentEndAt: string | null };
declare global { interface Window { turnstile?: { render: (target: HTMLElement, options: { sitekey: string; callback: (token: string) => void }) => void } } }

async function api<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`/api/commercial/${path}`, { cache: 'no-store', ...init });
  const body = await response.json() as T & { error?: string };
  if (!response.ok) throw new Error(body.error ?? 'Please try again.');
  return body;
}
const post = (body: unknown): RequestInit => ({ method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });

export default function CommercialApp({ turnstileSiteKey }: { turnstileSiteKey: string }) {
  const [phase, setPhase] = useState<'loading' | 'phone' | 'code' | 'billing' | 'desk'>('loading');
  const [phone, setPhone] = useState('');
  const [code, setCode] = useState('');
  const [turnstileToken, setTurnstileToken] = useState('');
  const turnstileRef = useRef<HTMLDivElement>(null);
  const [billing, setBilling] = useState<Billing | null>(null);
  const [settings, setSettings] = useState({ name: '', default_price_cents: 0 });
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [orders, setOrders] = useState<Order[]>([]);
  const [accounts,setAccounts]=useState<Account[]>([]);
  const [summary,setSummary]=useState<Summary|null>(null);
  const [showImport,setShowImport]=useState(false);
  const [collectionCustomer,setCollectionCustomer]=useState<Customer|null>(null);
  const [collectionCount,setCollectionCount]=useState(1);
  const [collectionReceipt,setCollectionReceipt]=useState('');
  const [supplierSharing,setSupplierSharing]=useState(false);
  const [payments, setPayments] = useState<Payment[]>([]);
  const [tab, setTab] = useState<'today'|'orders'|'customers'|'route'|'ledger'>('today');
  const [showSettings, setShowSettings] = useState(false);
  const [paymentCustomer, setPaymentCustomer] = useState<Customer | null>(null);
  const [search, setSearch] = useState('');
  const [editingCustomer, setEditingCustomer] = useState<Customer | null>(null);
  const [customerDraft, setCustomerDraft] = useState({ name: '', phone: '', address: '', area: '', usualQuantity: 2, frequencyDays: 7 });
  const [quickMode, setQuickMode] = useState<'order'|'customer'|null>(null);
  const [quickPhone, setQuickPhone] = useState('');
  const [lang, setLang] = useState<'en'|'ta'|'hi'>('en');
  const [deliverySearch,setDeliverySearch]=useState('');
  const [deliveryArea,setDeliveryArea]=useState<string|null>(null);
  const [newCustomer, setNewCustomer] = useState({ name: '', phone: '', address: '', area: '', usualQuantity: 2, frequencyDays: 7 });
  const [quantity, setQuantity] = useState(2);
  const [selected, setSelected] = useState<Customer | null>(null);
  const [selectedDelivery, setSelectedDelivery] = useState<Order | null>(null);
  const [returned, setReturned] = useState(0);
  const [paid, setPaid] = useState('0');
  const [requestLink, setRequestLink] = useState('');
  const [linkPhone, setLinkPhone] = useState('');
  const [notice, setNotice] = useState('');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);

  const refresh = useCallback(async () => {
    try {
      const data=await api<{billing:Billing;balances?:Account[];summary?:Summary;customers?:Customer[];orders?:Order[];payments?:Payment[];settings?:{name:string;default_price_cents:number}}>('bootstrap');
      const plan=data.billing;setBilling(plan);
      if(!sessionStorage.getItem('getcan-renewed'))void api('auth/refresh',post({})).then(()=>sessionStorage.setItem('getcan-renewed','1')).catch(()=>{});
      if(plan.status!=='active'||(plan.currentEndAt&&plan.currentEndAt<=new Date().toISOString())){setPhase('billing');return;}
      setAccounts(data.balances??[]);setSummary(data.summary??null);setCustomers(data.customers??[]);setOrders(data.orders??[]);setPayments(data.payments??[]);if(data.settings)setSettings(data.settings);setPhase('desk');setError('');
    } catch (e) { if (e instanceof Error && e.message.includes('Sign in')) setPhase('phone'); else { setError(e instanceof Error ? e.message : 'Could not load your desk.'); setPhase('phone'); } }
  }, []);
  useEffect(() => { void refresh(); const value = localStorage.getItem('getcan-language'); if (value === 'ta' || value === 'hi') setLang(value); }, [refresh]);
  useEffect(() => {
    if (phase !== 'phone' || !turnstileSiteKey || !turnstileRef.current) return;
    const render = () => { if (window.turnstile && turnstileRef.current && !turnstileRef.current.hasChildNodes()) window.turnstile.render(turnstileRef.current, { sitekey: turnstileSiteKey, callback: setTurnstileToken }); };
    if (window.turnstile) { render(); return; }
    const script = document.createElement('script'); script.src = 'https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit'; script.async = true; script.onload = render; document.head.appendChild(script);
    return () => { script.onload = null; };
  }, [phase, turnstileSiteKey]);

  function openQuick(mode: 'order'|'customer' = 'order', phone = '') { setQuickPhone(phone); setQuickMode(mode); setError(''); }
  async function quickDone(result: { id: number; newCustomer: boolean; requestLink?: string | null }, phoneValue: string) { setQuickMode(null); setNotice(quickMode === 'customer' ? 'Customer saved.' : `Order #${result.id} placed for ${phoneValue}.`); if (result.requestLink) { setSupplierSharing(false);setRequestLink(result.requestLink); setLinkPhone(phoneValue); } await refresh(); }
  function editCustomer(c: Customer) { setEditingCustomer(c); setCustomerDraft({ name: c.name, phone: c.phone, address: c.address, area: c.area, usualQuantity: c.usual_quantity, frequencyDays: c.frequency_days }); setError(''); }
  async function saveCustomerEdit() { if (!editingCustomer) return; setBusy(true); setError(''); try { await api('customers', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: editingCustomer.id, ...customerDraft }) }); setEditingCustomer(null); setNotice('Customer updated.'); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not update customer.'); } finally { setBusy(false); } }
  async function sendCode() { setBusy(true); setError(''); try { await api('auth/send', post({ phone, turnstileToken })); setPhase('code'); setNotice('Code sent to your mobile.'); } catch (e) { setError(e instanceof Error ? e.message : 'Could not send code.'); } finally { setBusy(false); } }
  async function verify() { setBusy(true); setError(''); try { await api('auth/verify', post({ phone, code })); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not verify code.'); } finally { setBusy(false); } }
  async function subscribe() { setBusy(true); setError(''); try { const result = await api<Billing>('billing', post({})); if (result.checkoutUrl) window.location.assign(result.checkoutUrl); else setNotice('Subscription created. Refresh to check payment.'); } catch (e) { setError(e instanceof Error ? e.message : 'Could not start payment.'); } finally { setBusy(false); } }
  async function addCustomer() { setBusy(true); setError(''); try { const result = await api<{ requestLink: string }>('customers', post(newCustomer)); setRequestLink(result.requestLink); setNotice('Customer added. Share their private request link below.'); setNewCustomer({ name: '', phone: '', address: '', area: '', usualQuantity: 2, frequencyDays: 7 }); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not add customer.'); } finally { setBusy(false); } }
  async function placeOrder() { if (!selected) return; setBusy(true); setError(''); try { await api('orders', post({ customerId: selected.id, quantity })); setNotice(`${quantity} cans requested for ${selected.name}.`); setSelected(null); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not place order.'); } finally { setBusy(false); } }
  async function advance(order: Order) { if (order.status === 'out_for_delivery') { setSelectedDelivery(order); setReturned(0); setPaid('0'); return; } const status = ['requested','accepted'].includes(order.status) ? 'out_for_delivery' : '';  if (!status) return; setBusy(true); setError(''); try { await api('orders', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: order.id, status }) }); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not update delivery.'); } finally { setBusy(false); } }
  async function completeDelivery() { if (!selectedDelivery) return; const paidCents = Math.round(Number(paid) * 100); if (!Number.isInteger(paidCents) || paidCents < 0 || paidCents > 10000000) { setError('Enter a valid payment amount.'); return; } setBusy(true); setError(''); try { await api('orders', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: selectedDelivery.id, status: 'delivered', returnedCans: returned, paidCents, method: 'cash' }) }); setSelectedDelivery(null); setNotice('Delivery completed and ledger updated.'); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not complete delivery.'); } finally { setBusy(false); } }
  async function saveSettings() { setBusy(true); setError(''); try { await api('settings', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: settings.name, defaultPriceCents: settings.default_price_cents }) }); setNotice('Distributor settings saved.'); setShowSettings(false); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not save settings.'); } finally { setBusy(false); } }
  async function startArea(area:string) { setBusy(true);setError('');try {const result=await api<{started:number}>('route',post({action:'start',area}));setNotice(`${result.started} orders out for delivery.`);await refresh();}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);} }
  function finish(order:Order){setSelectedDelivery(order);setReturned(0);setPaid('0');}
  async function shareCustomer(c:Customer){setBusy(true);setError('');try{const result=await api<{requestLink:string}>('customer-link',post({id:c.id}));setSupplierSharing(false);setRequestLink(result.requestLink);setLinkPhone(c.phone);}catch(e){setError(e instanceof Error?e.message:'Could not share link.');}finally{setBusy(false);}}
  async function shareSupplier(){setBusy(true);setError('');try{const result=await api<{inviteLink:string}>('invitation',post({}));setSupplierSharing(true);setRequestLink(result.inviteLink);setLinkPhone('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  function openCollection(c:Customer){setCollectionCustomer(c);setCollectionCount(Math.max(1,cansOut(c)));setCollectionReceipt(crypto.randomUUID());setError('');}
  async function collectCans(){if(!collectionCustomer)return;setBusy(true);setError('');try{await api('empty-cans',post({customerId:collectionCustomer.id,quantity:collectionCount,receipt:collectionReceipt}));setCollectionCustomer(null);setNotice(`${collectionCount} empty cans collected.`);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function recordPayment() { if (!paymentCustomer) return; const amountCents = Math.round(Number(paid) * 100); if (!Number.isInteger(amountCents) || amountCents < 1) { setError('Enter a payment amount.'); return; } setBusy(true); setError(''); try { await api('payments', post({ customerId: paymentCustomer.id, amountCents, method: 'cash' })); setPaymentCustomer(null); setNotice('Payment recorded.'); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not record payment.'); } finally { setBusy(false); } }
  async function logout() { await api('auth/logout', post({})); sessionStorage.removeItem('getcan-renewed'); setPhase('phone'); setBilling(null); setCustomers([]); setOrders([]); }

  const openOrders = orders.filter(o => o.status !== 'delivered');
  const newOrders = openOrders.filter(o => o.status === 'requested');
  const routeOrders = openOrders;
  const areaKey=(area:string)=>area.trim().toLowerCase();
  const areas=[...new Set(openOrders.map(o=>areaKey(o.area)))];
  const visibleDeliveries=openOrders.filter(o=>(deliveryArea===null||areaKey(o.area)===deliveryArea)&&`${o.customer} ${o.phone} ${o.area} ${o.address}`.toLowerCase().includes(deliverySearch.toLowerCase()));
  const balance=(c:Customer)=>accounts.find(a=>a.customer_id===c.id)?.balance_cents??0;
  const cansOut=(c:Customer)=>accounts.find(a=>a.customer_id===c.id)?.cans_out??0;
  const dueThisWeek = customers.filter(c => c.last_delivered_at && Date.parse(c.last_delivered_at) + c.frequency_days * 86400000 <= Date.now() + 7 * 86400000 && !orders.some(o => o.customer_id === c.id && o.status !== 'delivered'));
  return <main className="gc-app"><header className="gc-header"><span className="gc-brand"><img src="/icon-192.png" width="36" height="36" alt=""/> getcan<span>.</span></span>{phase === 'desk' && <button className="gc-quiet" onClick={logout}><LogOut size={16}/> Sign out</button>}</header>
    <div className="gc-customer-install"><InstallApp visible={phase === 'desk' || phase === 'billing'}/></div>
    {error && <div className="gc-alert" role="alert">{error}</div>}{notice && <div className="gc-notice" role="status"><Check size={18}/>{notice}<button onClick={() => setNotice('')} aria-label="Dismiss notice">×</button></div>}
    {requestLink && phase === 'desk' && <div className="gc-overlay" onClick={()=>setRequestLink('')}><section className="gc-dialog" role="dialog" aria-modal="true" aria-label="Share order link" onClick={e=>e.stopPropagation()}><button className="gc-close" onClick={()=>setRequestLink('')} aria-label="Close">×</button><h2>{tx(lang,supplierSharing?'Invite customers':'Share order link')}</h2><p>{supplierSharing?settings.name:linkPhone}</p><p>{supplierSharing?tx(lang,'Share this public link with new customers.'):tx(lang,'Customer can tap the can to order.')}</p><input aria-label="Customer order link" readOnly value={requestLink}/><div className="delivery-share-actions"><button className="gc-primary" onClick={()=>void navigator.clipboard.writeText(requestLink).then(()=>setNotice('Link copied.')).catch(()=>setError('Select the link and copy it.'))}><Copy size={18}/>Copy</button><a className="gc-primary" href={`https://wa.me/${linkPhone?'91'+linkPhone:''}?text=${encodeURIComponent(`${supplierSharing?'Join':'Order water from'} ${settings.name}: ${requestLink}`)}`} target="_blank" rel="noopener noreferrer">WhatsApp</a><a href={requestLink} target="_blank" rel="noopener noreferrer">Open order page</a></div></section></div>}
    {phase === 'loading' && <section className="gc-startup" aria-busy="true" aria-label="Opening delivery desk"><div className="gc-startup-heading"><h1>{tx(lang,'Today')}</h1><span>{tx(lang,'Opening your desk…')}</span></div><div className="gc-startup-actions">{['Take a new order','Deliver','Collect'].map((label,i)=><div key={label}><span>{i===0?<Plus size={28}/>:i===1?<Truck size={28}/>:<Wallet size={28}/>}</span><strong>{tx(lang,label)}</strong></div>)}</div><div className="gc-startup-placeholder"/></section>}
    {(phase === 'phone' || phase === 'code') && <section className="gc-login"><img className="gc-login-can" src="/icon-192.png" width="72" height="72" alt="GetCan watercan"/><h1>{phase === 'phone' ? 'Supplier login' : 'Enter OTP'}</h1>{phase === 'code' && <p>Sent to {phone}</p>}{phase === 'phone' ? <><label>Mobile number<input inputMode="tel" autoComplete="tel" placeholder="10-digit mobile number" value={phone} onChange={e => setPhone(e.target.value)} /></label><div ref={turnstileRef} className="gc-turnstile"/><button className="gc-primary" disabled={busy || !turnstileToken} onClick={sendCode}>Continue <ArrowRight size={18}/></button></> : <><label>Verification code<input inputMode="numeric" autoComplete="one-time-code" placeholder="Enter code" value={code} onChange={e => setCode(e.target.value)} /></label><button className="gc-primary" disabled={busy} onClick={verify}>Verify and continue <ArrowRight size={18}/></button><button className="gc-quiet" onClick={() => setPhase('phone')}>Change number</button></>}</section>}
    {phase === 'billing' && <section className="gc-login"><div className="gc-icon"><Truck size={35}/></div><span className="gc-eyebrow">GETCAN FOR DISTRIBUTORS</span><h1>Run every delivery in one place.</h1><p>Customers, one-tap requests, delivery rhythm, payments and empty cans.</p><div className="gc-plan"><strong>₹50 <small>/ month</small></strong><span>₹50/month core plan</span></div>{billing?.checkoutUrl ? <a className="gc-primary" href={billing.checkoutUrl}>Complete subscription <ArrowRight size={18}/></a> : <button className="gc-primary" disabled={busy} onClick={subscribe}>Start subscription <ArrowRight size={18}/></button>}<button className="gc-quiet" onClick={() => void refresh()}><RefreshCw size={16}/> I have paid — refresh</button></section>}
    {phase === 'desk' && <div className="gc-desk"><div className="gc-title"><div><span className="gc-eyebrow">{settings.name || 'GETCAN'}</span><h1>{tx(lang,tab === 'today' ? 'Today' : tab === 'route' ? 'Delivery' : tab[0].toUpperCase() + tab.slice(1))}</h1></div><div className="gc-title-actions"><select aria-label="Language" value={lang} onChange={e => { const value = e.target.value as 'en'|'ta'|'hi'; setLang(value); localStorage.setItem('getcan-language', value); }}><option value="en">English</option><option value="ta">தமிழ்</option><option value="hi">हिन्दी</option></select><button className="gc-quiet gc-icon-button" onClick={() => setShowSettings(true)} aria-label="Settings"><Settings2 size={19}/></button><button className="gc-primary gc-new-order" onClick={() => openQuick()}><Plus size={20}/>{tx(lang,'New order')}</button></div></div><nav className="gc-tabs" aria-label="Distributor sections">{([['today','Today'],['orders','Orders'],['customers','Customers'],['route','Delivery'],['ledger','Ledger']] as const).map(([id,label]) => <button key={id} aria-current={tab === id ? 'page' : undefined} className={tab === id ? 'active' : ''} onClick={() => { setTab(id); window.scrollTo({top:0,behavior:'instant'}); }}>{id === 'today' ? <Home size={23}/> : id === 'orders' ? <ClipboardList size={23}/> : id === 'customers' ? <Users size={23}/> : id === 'route' ? <Truck size={23}/> : <Wallet size={23}/>}<span>{tx(lang,label)}</span></button>)}</nav>
      {tab === 'today' && <><div className="work-actions"><button className="work-action work-order" onClick={() => openQuick()}><span className="work-icon"><Plus size={30}/></span><span className="work-text"><small>01 · {tx(lang,'ORDER')}</small><strong>{tx(lang,'Take a new order')}</strong><em>{tx(lang,'Search a customer or add one in the same step')}</em></span><ArrowRight size={23}/></button><button className="work-action" onClick={() => setTab('route')}><span className="work-icon"><Truck size={27}/></span><span className="work-text"><small>02 · {tx(lang,'DELIVERY')}</small><strong>{tx(lang,'Deliver')}</strong><em>{openOrders.length} {tx(lang,'Open')} · {openOrders.filter(o=>o.status==='out_for_delivery').length} {tx(lang,'On the way')}</em></span><ArrowRight size={21}/></button><button className="work-action" onClick={() => setTab('ledger')}><span className="work-icon"><Wallet size={27}/></span><span className="work-text"><small>03 · {tx(lang,'COLLECTION')}</small><strong>{tx(lang,'Collect')}</strong><em>₹{(customers.reduce((n,c) => n + Math.max(0,balance(c)),0)/100).toLocaleString('en-IN')} {tx(lang,'to collect')}</em></span><ArrowRight size={21}/></button></div><div className="gc-columns"><section className="gc-panel"><h2>{tx(lang,'New requests')} <span className="head-count">{newOrders.length}</span></h2><div className="gc-list">{newOrders.slice(0,5).map(o => <div key={o.id} className="gc-order"><span><strong>{o.customer}</strong><small>{o.quantity} cans · ₹{(o.quantity * o.price_cents / 100).toFixed(0)}</small></span><button disabled={busy} onClick={() => advance(o)}>{tx(lang,'Out for delivery')}</button></div>)}{!newOrders.length && <p className="gc-empty">{tx(lang,'No new requests.')}</p>}</div></section><section className="gc-panel"><h2>{tx(lang,'May need water soon')} <span className="head-count">{dueThisWeek.length}</span></h2><div className="gc-list">{dueThisWeek.slice(0,5).map(c => <button key={c.id} className="gc-person" onClick={() => { openQuick('order', c.phone); }}><span className="gc-avatar"><Droplets size={18}/></span><span><strong>{c.name}</strong><small>{c.usual_quantity} usual cans · every {c.frequency_days} days</small></span><Plus size={18}/></button>)}{!dueThisWeek.length && <p className="gc-empty">{tx(lang,'No customers predicted this week yet.')}</p>}</div></section></div></>}
      {tab === 'orders' && <section className="gc-panel"><div className="gc-panel-head"><h2>{tx(lang,'All orders')}</h2><button className="gc-quiet" onClick={() => openQuick()}><Plus size={17}/>{tx(lang,'New order')}</button></div><button className="order-search-launch" onClick={() => openQuick()}><Search size={22}/><span><strong>{tx(lang,'Take a new order')}</strong><small>{tx(lang,'Search by name or mobile. New customers are added while ordering.')}</small></span><Plus size={21}/></button><div className="gc-list">{orders.map(o => <div key={o.id} className="gc-order"><span><strong>{o.customer}</strong><small>#{o.id} · {o.quantity} cans · ₹{(o.quantity * o.price_cents / 100).toFixed(0)} · {o.status.replaceAll('_', ' ')}</small></span>{o.status !== 'delivered' && <button disabled={busy} onClick={() => advance(o)}>{tx(lang,o.status === 'out_for_delivery' ? 'Mark delivered' : 'Out for delivery')}</button>}</div>)}{!orders.length && <p className="gc-empty">Orders will appear here.</p>}</div></section>}
      {tab === 'customers' && <section className="gc-panel"><div className="gc-panel-head"><h2>{tx(lang,'Customers')}</h2><button className="gc-primary" onClick={() => openQuick('customer')}><Plus size={17}/>{tx(lang,'Add customer')}</button></div><div className="gc-customer-tools"><button onClick={()=>setShowImport(true)}>{tx(lang,'Import customers')}</button><button disabled={busy} onClick={()=>void shareSupplier()}>{tx(lang,'Invite customers')}</button></div><input placeholder={tx(lang,"Search name or phone")} aria-label="Search customers" value={search} onChange={e => setSearch(e.target.value)}/><div className="gc-list">{customers.filter(c => `${c.name} ${c.phone} ${c.area} ${c.address}`.toLowerCase().includes(search.toLowerCase())).map(c => <div key={c.id} className="gc-person"><span className="gc-avatar">{c.name[0]?.toUpperCase()}</span><span><strong>{c.name}</strong><small>{c.phone} · {c.area || tx(lang,'No area added')} · {c.usual_quantity} {tx(lang,'cans')}</small></span><div className="gc-customer-actions"><button disabled={busy} onClick={() => void shareCustomer(c)}>{tx(lang,'Share order link')}</button><button onClick={() => editCustomer(c)}>{tx(lang,'Edit')}</button><button onClick={() => openQuick('order',c.phone)}>{tx(lang,'Order')}</button></div></div>)}{!customers.length && <p className="gc-empty">Add a number to start your customer book.</p>}</div></section>}
      {tab === 'route' && <section className="gc-panel"><div className="gc-panel-head"><h2>{tx(lang,'Delivery')}</h2><span>{openOrders.length} {tx(lang,'Open')}</span></div><label className="delivery-search"><Search size={20}/><input placeholder={tx(lang,'Search name, mobile or area')} aria-label={tx(lang,'Search name, mobile or area')} value={deliverySearch} onChange={e=>setDeliverySearch(e.target.value)}/></label><div className="delivery-area-filters"><button className={deliveryArea===null?'active':''} onClick={()=>setDeliveryArea(null)}>{tx(lang,'All')}</button>{areas.map(area=><button key={area} className={deliveryArea===area?'active':''} onClick={()=>setDeliveryArea(area)}>{openOrders.find(o=>areaKey(o.area)===area)?.area || tx(lang,'No area added')} · {openOrders.filter(o=>areaKey(o.area)===area).length}</button>)}</div>{areas.filter(area=>visibleDeliveries.some(o=>areaKey(o.area)===area)).map(area=>{const group=visibleDeliveries.filter(o=>areaKey(o.area)===area);const ready=openOrders.filter(o=>areaKey(o.area)===area&&o.status!=='out_for_delivery');return <section key={area} className="delivery-area"><div className="gc-panel-head"><div><h3>{group[0].area || tx(lang,'No area added')}</h3><small>{group.length} {tx(lang,'Orders')} · {group.reduce((n,o)=>n+o.quantity,0)} {tx(lang,'cans')}</small></div>{ready.length>0&&<button className="gc-primary" disabled={busy} onClick={()=>void startArea(area)}><Truck size={17}/>{tx(lang,'Out for delivery')} · {ready.length}</button>}</div><div className="gc-list">{group.map(o=><div key={o.id} className="delivery-customer"><div className="delivery-person"><strong>{o.customer}</strong><small>{o.phone} · {o.area || tx(lang,'No area added')}</small><small>{o.address}</small><span className={o.status==='out_for_delivery'?'delivery-status onway':'delivery-status'}>{tx(lang,o.status==='out_for_delivery'?'Out for delivery':'Ready to dispatch')}</span></div><div className="delivery-total"><strong>{o.quantity} {tx(lang,'cans')}</strong><small>₹{(o.quantity*o.price_cents/100).toLocaleString('en-IN')}</small></div><div className="delivery-actions"><a href={`tel:${o.phone}`} aria-label={`${tx(lang,'Call')} ${o.customer}`}><Phone size={18}/>{tx(lang,'Call')}</a><button disabled={busy} className="gc-primary" onClick={()=>finish(o)}><Check size={18}/>{tx(lang,'Mark delivered')}</button></div></div>)}</div></section>})}{!visibleDeliveries.length&&<p className="gc-empty">{tx(lang,'No orders here')}</p>}</section>}
      {tab === 'ledger' && <section className="gc-panel"><h2>{tx(lang,'Customer balances')}</h2>{summary&&<><p className="gc-summary-date">{tx(lang,'Today')} · {new Date(summary.day+'T12:00:00+05:30').toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</p><div className="gc-daily-summary">{[['Sales today',`₹${(summary.sales_cents/100).toLocaleString('en-IN')}`],['Collected today',`₹${(summary.collected_cents/100).toLocaleString('en-IN')}`],['Cans delivered',summary.delivered_cans],['Empties collected',summary.returned_cans],['Total dues',`₹${(summary.dues_cents/100).toLocaleString('en-IN')}`],['Cans with customers',summary.cans_out]].map(([label,value])=><div key={label}><small>{tx(lang,String(label))}</small><strong>{value}</strong></div>)}</div><small>{tx(lang,'Dues and cans with customers include full history.')}{summary.credit_cents>0&&` · Customer credit ₹${(summary.credit_cents/100).toLocaleString('en-IN')}`}</small></>}<div className="gc-list">{customers.map(c => <div key={c.id} className="gc-order"><span><strong>{c.name}</strong><small>{cansOut(c)} empty cans out</small></span><div><strong>{balance(c)<0?tx(lang,'Credit'):tx(lang,'Due')} ₹{(Math.abs(balance(c))/100).toFixed(0)}</strong><button onClick={() => { setPaymentCustomer(c); setPaid(String(Math.max(0,balance(c))/100)); }}>{tx(lang,'Payment')}</button><button disabled={busy||cansOut(c)<=0} onClick={()=>openCollection(c)}>{tx(lang,'Collect empty cans')}</button></div></div>)}{!customers.length && <p className="gc-empty">Balances appear after adding customers.</p>}</div></section>}
    <footer className="gc-plan-footer">{billing?.trialEnd && <span>Free access until {new Date(billing.trialEnd).toLocaleDateString('en-IN',{day:'numeric',month:'short'})} · then ₹50/month</span>}</footer>
    </div>}
    {showImport&&phase==='desk'&&<CustomerImport onClose={()=>setShowImport(false)} onDone={async message=>{setNotice(message);await refresh();}}/>}
    {collectionCustomer&&phase==='desk'&&<div className="gc-overlay" onClick={()=>setCollectionCustomer(null)}><section className="gc-dialog" role="dialog" aria-modal="true" aria-label="Collect empty cans" onClick={e=>e.stopPropagation()}><button className="gc-close" aria-label="Close" onClick={()=>setCollectionCustomer(null)}>×</button><h2>{tx(lang,'Collect empty cans')}</h2><p>{collectionCustomer.name} · {cansOut(collectionCustomer)} {tx(lang,'Cans with customers')}</p><label>{tx(lang,'Empty cans collected')}<div className="gc-stepper"><button disabled={collectionCount<=1} onClick={()=>setCollectionCount(n=>n-1)} aria-label="One fewer can"><Minus/></button><input aria-label="Number of empty cans" type="number" min="1" max={cansOut(collectionCustomer)} value={collectionCount} onChange={e=>setCollectionCount(Number(e.target.value))}/><button disabled={collectionCount>=cansOut(collectionCustomer)} onClick={()=>setCollectionCount(n=>n+1)} aria-label="One more can"><Plus/></button></div></label>{error&&<p className="quick-error" role="alert">{error}</p>}<button className="gc-primary" disabled={busy||!Number.isInteger(collectionCount)||collectionCount<1||collectionCount>cansOut(collectionCustomer)} onClick={()=>void collectCans()}>{tx(lang,'Save collection')} <Check size={19}/></button></section></div>}
    {showSettings && phase === 'desk' && <div className="gc-overlay" onClick={() => setShowSettings(false)}><section className="gc-dialog" role="dialog" aria-modal="true" aria-label="Distributor settings" onClick={e => e.stopPropagation()}><button className="gc-close" onClick={() => setShowSettings(false)}>×</button><h2>Settings</h2><label>Distributor name<input value={settings.name} onChange={e => setSettings({ ...settings, name: e.target.value })}/></label><label>Price per 20 L can (₹)<input type="number" min="0" step="0.01" value={settings.default_price_cents / 100} onChange={e => setSettings({ ...settings, default_price_cents: Math.round(Number(e.target.value) * 100) })}/></label><p>One price applies to new orders. Existing orders keep their saved price.</p><button className="gc-primary" disabled={busy} onClick={saveSettings}>Save settings</button></section></div>}
    {editingCustomer && phase === 'desk' && <div className="gc-overlay" onClick={() => setEditingCustomer(null)}><section className="gc-dialog" role="dialog" aria-modal="true" aria-label="Edit customer" onClick={e => e.stopPropagation()}><button className="gc-close" onClick={() => setEditingCustomer(null)}>×</button><h2>{tx(lang,'Edit customer')}</h2><label>{tx(lang,'Name')}<input value={customerDraft.name} onChange={e => setCustomerDraft({ ...customerDraft, name: e.target.value })}/></label><label>{tx(lang,'Mobile')}<input inputMode="tel" value={customerDraft.phone} onChange={e => setCustomerDraft({ ...customerDraft, phone: e.target.value })}/></label><label>{tx(lang,'Area')}<input value={customerDraft.area} onChange={e=>setCustomerDraft({...customerDraft,area:e.target.value})}/></label><label>{tx(lang,'Address')}<input value={customerDraft.address} onChange={e => setCustomerDraft({ ...customerDraft, address: e.target.value })}/></label><label>{tx(lang,'Usual cans')}<input type="number" min="1" max="50" value={customerDraft.usualQuantity} onChange={e => setCustomerDraft({ ...customerDraft, usualQuantity: Number(e.target.value) })}/></label><label>{tx(lang,'Days between deliveries')}<input type="number" min="1" max="90" value={customerDraft.frequencyDays} onChange={e => setCustomerDraft({ ...customerDraft, frequencyDays: Number(e.target.value) })}/></label><button className="gc-primary" disabled={busy} onClick={saveCustomerEdit}>{tx(lang,'Save customer')}</button></section></div>}
    {paymentCustomer && phase === 'desk' && <div className="gc-overlay" onClick={() => setPaymentCustomer(null)}><section className="gc-dialog" role="dialog" aria-modal="true" aria-label="Record payment" onClick={e => e.stopPropagation()}><button className="gc-close" onClick={() => setPaymentCustomer(null)}>×</button><h2>Payment from {paymentCustomer.name}</h2><p>Balance ₹{(balance(paymentCustomer)/100).toFixed(0)}</p><label>Cash received (₹)<input type="number" min="0.01" step="0.01" value={paid} onChange={e => setPaid(e.target.value)}/></label><button className="gc-primary" disabled={busy} onClick={recordPayment}>Record payment</button></section></div>}
    {quickMode && phase === 'desk' && <QuickOrder key={`${quickMode}-${quickPhone}`} endpoint={quickMode === 'order' ? '/api/commercial/quick-order' : '/api/commercial/customers'} lookupEndpoint="/api/commercial/quick-order" people={customers} priceCents={settings.default_price_cents} initialPhone={quickPhone} lang={lang} saveOnly={quickMode === 'customer'} onClose={() => setQuickMode(null)} onDone={quickDone}/>}
    {selectedDelivery && phase === 'desk' && <div className="gc-overlay" onClick={() => setSelectedDelivery(null)}><section className="gc-dialog" role="dialog" aria-modal="true" aria-label="Complete delivery" onClick={e => e.stopPropagation()}><button className="gc-close" onClick={() => setSelectedDelivery(null)}>×</button><span className="gc-eyebrow">COMPLETE DELIVERY</span><h2>{selectedDelivery.customer}</h2><p>{selectedDelivery.quantity} cans · ₹{(selectedDelivery.quantity * selectedDelivery.price_cents / 100).toFixed(0)} total</p><label>{tx(lang,'Empty cans collected')}<div className="gc-stepper"><button disabled={returned <= 0} onClick={() => setReturned(n => n - 1)} aria-label="One fewer empty can"><Minus/></button><strong>{returned}</strong><button disabled={returned >= Math.min(100,(accounts.find(c=>c.customer_id===selectedDelivery.customer_id)?.cans_out??0) + selectedDelivery.quantity)} onClick={() => setReturned(n => n + 1)} aria-label="One more empty can"><Plus/></button></div></label><label>{tx(lang,'Cash received (₹)')}<input inputMode="decimal" type="number" min="0" step="0.01" value={paid} onChange={e => setPaid(e.target.value)}/></label><button className="gc-primary" disabled={busy} onClick={completeDelivery}>{tx(lang,'Mark delivered')} <Check size={19}/></button></section></div>}
  </main>;
}
