'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import CustomerImport from '@/components/customer-import';
import InstallApp, { useInstallPrompt } from '@/components/install-app';
import LanguageSelect from '@/components/language-select';
import QuickOrder from '@/components/quick-order';
import { tx, type Language } from '@/components/labels';
import { chime, enablePush, pushEnabled, pushSupported } from '@/components/push-alerts';
import Statement from '@/components/statement';
import { clearOffline, flushOutbox, isNetworkError, outboxSize, queueRequest, queuedDeliveries, readSnapshot, saveSnapshot } from '@/components/offline';
import { ArrowRight, Bell, BellRing, Check, Copy, Droplets, FileText, LogOut, Minus, Plus, RefreshCw, Truck, Users, Wallet, Settings2, Phone, ClipboardList, Search, Home, Link2, MessageCircle, Download, IndianRupee, Store } from 'lucide-react';

type Customer = { id: number; name: string; phone: string; address: string; area: string; usual_quantity: number; frequency_days: number; last_delivered_at: string | null };
type Order = { id: number; customer_id: number; customer: string; quantity: number; status: string; price_cents: number; returned_cans: number; route_rank: number; phone: string; address: string; area: string };
type Payment = { id: number; customer_id: number; amount_cents: number };
type Account={customer_id:number;balance_cents:number;cans_out:number};
type Summary={day:string;sales_cents:number;collected_cents:number;delivered_cans:number;returned_cans:number;dues_cents:number;credit_cents:number;cans_out:number};
type Settings = { name: string; default_price_cents: number; upi_id: string; onboarded?: boolean };
type Billing = { trialEnd?: string | null; status: string; checkoutUrl: string | null; currentEndAt: string | null };
declare global { interface Window { turnstile?: { render: (target: HTMLElement, options: { sitekey: string; callback: (token: string) => void }) => void } } }

async function api<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`/api/commercial/${path}`, { cache: 'no-store', ...init });
  const body = await response.json() as T & { error?: string };
  if (!response.ok) throw new Error(body.error ?? 'Please try again.');
  return body;
}
const post = (body: unknown): RequestInit => ({ method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
const DEFAULT_NAME = 'My distribution';
const locale = (lang: Language) => lang === 'ta' ? 'ta-IN' : lang === 'hi' ? 'hi-IN' : 'en-IN';
function greeting() { const hour = new Date().getHours(); return hour < 12 ? 'Good morning' : hour < 17 ? 'Good afternoon' : 'Good evening'; }

export default function CommercialApp({ turnstileSiteKey }: { turnstileSiteKey: string }) {
  const [phase, setPhase] = useState<'loading' | 'phone' | 'code' | 'billing' | 'setup' | 'desk'>('loading');
  const [phone, setPhone] = useState('');
  const [code, setCode] = useState('');
  const [turnstileToken, setTurnstileToken] = useState('');
  const turnstileRef = useRef<HTMLDivElement>(null);
  const [billing, setBilling] = useState<Billing | null>(null);
  const [settings, setSettings] = useState<Settings>({ name: '', default_price_cents: 0, upi_id: '' });
  const [setupStep, setSetupStep] = useState<'name'|'price'|'install'>('name');
  const [setupName, setSetupName] = useState('');
  const [setupPrice, setSetupPrice] = useState('');
  const [installHelp, setInstallHelp] = useState(false);
  const installer = useInstallPrompt();
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [orders, setOrders] = useState<Order[]>([]);
  const [accounts,setAccounts]=useState<Account[]>([]);
  const [summary,setSummary]=useState<Summary|null>(null);
  const [showImport,setShowImport]=useState(false);
  const [collectionCustomer,setCollectionCustomer]=useState<Customer|null>(null);
  const [collectionCount,setCollectionCount]=useState(1);
  const [collectionReceipt,setCollectionReceipt]=useState('');
  const [supplierSharing,setSupplierSharing]=useState(false);
  const [payments, setPayments] = useState<Payment[]>([]);
  const [tab, setTab] = useState<'today'|'orders'|'customers'|'route'|'ledger'>('today');
  const [showSettings, setShowSettings] = useState(false);
  const [paymentCustomer, setPaymentCustomer] = useState<Customer | null>(null);
  const [search, setSearch] = useState('');
  const [editingCustomer, setEditingCustomer] = useState<Customer | null>(null);
  const [customerDraft, setCustomerDraft] = useState({ name: '', phone: '', address: '', area: '', usualQuantity: 2, frequencyDays: 7 });
  const [quickMode, setQuickMode] = useState<'order'|'customer'|null>(null);
  const [quickPhone, setQuickPhone] = useState('');
  const [lang, setLang] = useState<Language>('en');
  const [deliverySearch,setDeliverySearch]=useState('');
  const [deliveryArea,setDeliveryArea]=useState<string|null>(null);
  const [newCustomer, setNewCustomer] = useState({ name: '', phone: '', address: '', area: '', usualQuantity: 2, frequencyDays: 7 });
  const [quantity, setQuantity] = useState(2);
  const [selected, setSelected] = useState<Customer | null>(null);
  const [selectedDelivery, setSelectedDelivery] = useState<Order | null>(null);
  const [returned, setReturned] = useState(0);
  const [paid, setPaid] = useState('0');
  const [requestLink, setRequestLink] = useState('');
  const [linkPhone, setLinkPhone] = useState('');
  const [notice, setNotice] = useState('');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const [pushKey, setPushKey] = useState<string|null>(null);
  const [alertsOn, setAlertsOn] = useState(false);
  const [offlineSince, setOfflineSince] = useState<string|null>(null);
  const [pending, setPending] = useState(0);
  const [linkCustomer, setLinkCustomer] = useState<Customer|null>(null);
  const [reminder, setReminder] = useState(false);
  const [statementCustomer, setStatementCustomer] = useState<Customer|null>(null);
  const [method, setMethod] = useState<'cash'|'upi'>('cash');
  const knownRequests = useRef<Set<number>|null>(null);

  const refresh = useCallback(async () => {
    try {
      type Desk={billing:Billing;balances?:Account[];summary?:Summary;customers?:Customer[];orders?:Order[];payments?:Payment[];settings?:Settings;pushKey?:string|null};
      let data:Desk,problems:string[]=[];
      try{problems=await flushOutbox();data=await api<Desk>('bootstrap');setOfflineSince(null);if(data.orders)saveSnapshot(data);}
      catch(e){const saved=isNetworkError(e)?readSnapshot<Desk>():null;if(!saved)throw e;data=saved.data;setOfflineSince(saved.savedAt);}
      setPending(outboxSize());
      const done=queuedDeliveries();if(done.length)data={...data,orders:data.orders?.map(o=>done.includes(o.id)?{...o,status:'delivered'}:o)};
      const requested=(data.orders??[]).filter(o=>o.status==='requested').map(o=>o.id);
      if(knownRequests.current&&requested.some(id=>!knownRequests.current!.has(id))){chime();setNotice('New water request');}
      knownRequests.current=new Set(requested);
      setPushKey(data.pushKey??null);
      const plan=data.billing;setBilling(plan);
      if(!sessionStorage.getItem('getcan-renewed'))void api('auth/refresh',post({})).then(()=>sessionStorage.setItem('getcan-renewed','1')).catch(()=>{});
      if(plan.status!=='active'||(plan.currentEndAt&&plan.currentEndAt<=new Date().toISOString())){setPhase('billing');return;}
      // First sign-in: ask for the business name and can price before opening the desk.
      if(data.settings&&data.settings.onboarded===false){const s=data.settings;setSettings(s);setSetupName(s.name===DEFAULT_NAME?'':s.name);setSetupPrice('');setSetupStep('name');setPhase('setup');return;}
      setAccounts(data.balances??[]);setSummary(data.summary??null);setCustomers(data.customers??[]);setOrders(data.orders??[]);setPayments(data.payments??[]);if(data.settings)setSettings(data.settings);setPhase('desk');setError(problems.join(' '));
    } catch (e) { if (e instanceof Error && e.message.includes('Sign in')) setPhase('phone'); else { setError(e instanceof Error ? e.message : 'Could not load your desk.'); setPhase('phone'); } }
  }, []);
  useEffect(() => { void refresh(); const value = localStorage.getItem('getcan-language'); if (value === 'ta' || value === 'hi') setLang(value); }, [refresh]);
  useEffect(() => {
    if (phase !== 'desk') return;
    // Keep the desk current so new requests are heard while the app is open.
    // Poll a small signature and reload the full desk only when orders changed.
    let last = '';
    const poll = async () => { if (document.visibilityState !== 'visible') return; try { const { signature } = await api<{ signature: string }>('pulse'); if (last && signature !== last) await refresh(); last = signature; } catch { /* offline or signed out: the next full refresh reports it */ } };
    void poll();
    const timer = setInterval(() => void poll(), 20000);
    const wake = () => { if (document.visibilityState === 'visible') void refresh(); };
    document.addEventListener('visibilitychange', wake); window.addEventListener('online', wake);
    const check = setTimeout(() => void pushEnabled().then(setAlertsOn), 0);
    return () => { clearInterval(timer); clearTimeout(check); document.removeEventListener('visibilitychange', wake); window.removeEventListener('online', wake); };
  }, [phase, refresh]);
  useEffect(() => {
    if (phase !== 'phone' || !turnstileSiteKey || !turnstileRef.current) return;
    const render = () => { if (window.turnstile && turnstileRef.current && !turnstileRef.current.hasChildNodes()) window.turnstile.render(turnstileRef.current, { sitekey: turnstileSiteKey, callback: setTurnstileToken }); };
    if (window.turnstile) { render(); return; }
    const script = document.createElement('script'); script.src = 'https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit'; script.async = true; script.onload = render; document.head.appendChild(script);
    return () => { script.onload = null; };
  }, [phase, turnstileSiteKey]);

  function chooseLanguage(value: Language) { setLang(value); localStorage.setItem('getcan-language', value); }

  function openQuick(mode: 'order'|'customer' = 'order', phone = '') { setQuickPhone(phone); setQuickMode(mode); setError(''); }
  async function quickDone(result: { id: number; newCustomer: boolean; requestLink?: string | null }, phoneValue: string) { setQuickMode(null); setNotice(quickMode === 'customer' ? 'Customer saved.' : `Order #${result.id} placed for ${phoneValue}.`); if (result.requestLink) { setSupplierSharing(false);setReminder(false);setLinkCustomer(null);setRequestLink(result.requestLink); setLinkPhone(phoneValue); } await refresh(); }
  function editCustomer(c: Customer) { setEditingCustomer(c); setCustomerDraft({ name: c.name, phone: c.phone, address: c.address, area: c.area, usualQuantity: c.usual_quantity, frequencyDays: c.frequency_days }); setError(''); }
  async function saveCustomerEdit() { if (!editingCustomer) return; setBusy(true); setError(''); try { await api('customers', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: editingCustomer.id, ...customerDraft }) }); setEditingCustomer(null); setNotice('Customer updated.'); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not update customer.'); } finally { setBusy(false); } }
  async function sendCode() { setBusy(true); setError(''); try { await api('auth/send', post({ phone, turnstileToken })); setPhase('code'); setNotice('Code sent to your mobile.'); } catch (e) { setError(e instanceof Error ? e.message : 'Could not send code.'); } finally { setBusy(false); } }
  async function verify() { setBusy(true); setError(''); try { await api('auth/verify', post({ phone, code })); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not verify code.'); } finally { setBusy(false); } }
  async function subscribe() { setBusy(true); setError(''); try { const result = await api<Billing>('billing', post({})); if (result.checkoutUrl) window.location.assign(result.checkoutUrl); else setNotice('Subscription created. Refresh to check payment.'); } catch (e) { setError(e instanceof Error ? e.message : 'Could not start payment.'); } finally { setBusy(false); } }
  async function addCustomer() { setBusy(true); setError(''); try { const result = await api<{ requestLink: string }>('customers', post(newCustomer)); setRequestLink(result.requestLink); setNotice('Customer added. Share their private request link below.'); setNewCustomer({ name: '', phone: '', address: '', area: '', usualQuantity: 2, frequencyDays: 7 }); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not add customer.'); } finally { setBusy(false); } }
  async function placeOrder() { if (!selected) return; setBusy(true); setError(''); try { await api('orders', post({ customerId: selected.id, quantity })); setNotice(`${quantity} cans requested for ${selected.name}.`); setSelected(null); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not place order.'); } finally { setBusy(false); } }
  async function advance(order: Order) { if (order.status === 'out_for_delivery') { setSelectedDelivery(order); setReturned(0); setPaid('0'); setMethod('cash'); return; } const status = ['requested','accepted'].includes(order.status) ? 'out_for_delivery' : '';  if (!status) return; setBusy(true); setError(''); try { await api('orders', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: order.id, status }) }); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not update delivery.'); } finally { setBusy(false); } }
  async function completeDelivery() { if (!selectedDelivery) return; const paidCents = Math.round(Number(paid) * 100); if (!Number.isInteger(paidCents) || paidCents < 0 || paidCents > 10000000) { setError('Enter a valid payment amount.'); return; } const body = { id: selectedDelivery.id, status: 'delivered', returnedCans: returned, paidCents, method }; setBusy(true); setError(''); try { await api('orders', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); setSelectedDelivery(null); setNotice('Delivery completed and ledger updated.'); await refresh(); } catch (e) { if (isNetworkError(e)) { queueRequest('orders', 'PATCH', body); setOrders(list => list.map(o => o.id === body.id ? { ...o, status: 'delivered' } : o)); setPending(outboxSize()); setSelectedDelivery(null); setNotice('Saved offline. It will be sent when you are back online.'); } else setError(e instanceof Error ? e.message : 'Could not complete delivery.'); } finally { setBusy(false); } }
  async function saveSettings() { setBusy(true); setError(''); try { await api('settings', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: settings.name, defaultPriceCents: settings.default_price_cents, upiId: settings.upi_id }) }); setNotice('Distributor settings saved.'); setShowSettings(false); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not save settings.'); } finally { setBusy(false); } }
  async function startArea(area:string) { setBusy(true);setError('');try {const result=await api<{started:number}>('route',post({action:'start',area}));setNotice(`${result.started} orders out for delivery.`);await refresh();}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);} }
  function finish(order:Order){setSelectedDelivery(order);setReturned(0);setPaid('0');setMethod('cash');}
  async function shareCustomer(c:Customer,remind=false){setBusy(true);setError('');try{const result=await api<{requestLink:string}>('customer-link',post({id:c.id}));setSupplierSharing(false);setReminder(remind);setLinkCustomer(c);setRequestLink(result.requestLink);setLinkPhone(c.phone);}catch(e){setError(e instanceof Error?e.message:'Could not share link.');}finally{setBusy(false);}}
  async function resetLink(){if(!linkCustomer||!window.confirm(tx(lang,'Make a new link? The old link will stop working.')))return;setBusy(true);setError('');try{const result=await api<{requestLink:string}>('customer-link',post({id:linkCustomer.id,reset:true}));setRequestLink(result.requestLink);setNotice('New link ready. The old link no longer works.');}catch(e){setError(e instanceof Error?e.message:'Could not make a new link.');}finally{setBusy(false);}}
  async function turnOnAlerts(){if(!pushKey)return;setBusy(true);setError('');try{await enablePush(pushKey);setAlertsOn(true);setNotice('Alerts on');}catch(e){setError(e instanceof Error?e.message:'Could not turn on alerts.');}finally{setBusy(false);}}
  async function shareSupplier(){setBusy(true);setError('');try{const result=await api<{inviteLink:string}>('invitation',post({}));setSupplierSharing(true);setReminder(false);setLinkCustomer(null);setRequestLink(result.inviteLink);setLinkPhone('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  function openCollection(c:Customer){setCollectionCustomer(c);setCollectionCount(Math.max(1,cansOut(c)));setCollectionReceipt(crypto.randomUUID());setError('');}
  async function collectCans(){if(!collectionCustomer)return;const body={customerId:collectionCustomer.id,quantity:collectionCount,receipt:collectionReceipt};setBusy(true);setError('');try{await api('empty-cans',post(body));setCollectionCustomer(null);setNotice(`${collectionCount} empty cans collected.`);await refresh();}catch(e){if(isNetworkError(e)){queueRequest('empty-cans','POST',body);setAccounts(list=>list.map(a=>a.customer_id===body.customerId?{...a,cans_out:a.cans_out-body.quantity}:a));setPending(outboxSize());setCollectionCustomer(null);setNotice('Saved offline. It will be sent when you are back online.');}else setError((e as Error).message);}finally{setBusy(false);}}
  async function recordPayment() { if (!paymentCustomer) return; const amountCents = Math.round(Number(paid) * 100); if (!Number.isInteger(amountCents) || amountCents < 1) { setError('Enter a payment amount.'); return; } setBusy(true); setError(''); try { await api('payments', post({ customerId: paymentCustomer.id, amountCents, method })); setPaymentCustomer(null); setNotice('Payment recorded.'); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not record payment.'); } finally { setBusy(false); } }
  function nameNext() { if (!setupName.trim()) { setError(tx(lang,'Enter your business name.')); return; } setError(''); setSetupStep('price'); }
  async function saveSetup() {
    const cents = Math.round(Number(setupPrice) * 100);
    if (!setupPrice.trim() || !Number.isInteger(cents) || cents < 1 || cents > 100000) { setError(tx(lang,'Enter a price between ₹1 and ₹1000.')); return; }
    setBusy(true); setError('');
    try {
      await api('settings', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: setupName.trim(), defaultPriceCents: cents, upiId: settings.upi_id }) });
      if (installer.installed) await refresh(); else { setInstallHelp(false); setSetupStep('install'); }
    } catch (e) { setError(e instanceof Error ? e.message : 'Could not save.'); } finally { setBusy(false); }
  }
  async function installFromSetup() { const outcome = await installer.install(); if (outcome === 'accepted') await refresh(); else if (outcome === 'unavailable') setInstallHelp(true); }
  async function logout() { setShowSettings(false); await api('auth/logout', post({})); clearOffline(); knownRequests.current = null; sessionStorage.removeItem('getcan-renewed'); setPhase('phone'); setBilling(null); setCustomers([]); setOrders([]); }

  const methodPicker = <div className="gc-payment-method" role="group" aria-label={tx(lang,'Payment method')}>{(['cash','upi'] as const).map(m => <button key={m} type="button" className={method === m ? 'active' : ''} aria-pressed={method === m} onClick={() => setMethod(m)}>{tx(lang, m === 'cash' ? 'Cash' : 'UPI')}</button>)}</div>;
  const openOrders = orders.filter(o => o.status !== 'delivered');
  const newOrders = openOrders.filter(o => o.status === 'requested');
  const routeOrders = openOrders;
  const areaKey=(area:string)=>area.trim().toLowerCase();
  const areas=[...new Set(openOrders.map(o=>areaKey(o.area)))];
  const visibleDeliveries=openOrders.filter(o=>(deliveryArea===null||areaKey(o.area)===deliveryArea)&&`${o.customer} ${o.phone} ${o.area} ${o.address}`.toLowerCase().includes(deliverySearch.toLowerCase()));
  const balance=(c:Customer)=>accounts.find(a=>a.customer_id===c.id)?.balance_cents??0;
  const cansOut=(c:Customer)=>accounts.find(a=>a.customer_id===c.id)?.cans_out??0;
  const dueThisWeek = customers.filter(c => c.last_delivered_at && Date.parse(c.last_delivered_at) + c.frequency_days * 86400000 <= Date.now() + 7 * 86400000 && !orders.some(o => o.customer_id === c.id && o.status !== 'delivered'));
  return <main className="gc-app"><header className="gc-header"><span className="gc-brand"><img src="/icon-192.png" width="36" height="36" alt=""/> getcan<span>.</span></span></header>
    <div className="gc-customer-install"><InstallApp visible={phase === 'billing'}/></div>
    {error && <div className="gc-alert" role="alert">{error}</div>}{notice && <div className="gc-notice" role="status"><Check size={18}/>{tx(lang,notice)}<button onClick={() => setNotice('')} aria-label="Dismiss notice">×</button></div>}
    {phase === 'desk' && (offlineSince || pending > 0) && <div className="gc-offline" role="status">{offlineSince && `${tx(lang,'Offline · showing saved data')} · ${new Date(offlineSince).toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'})}`}{offlineSince && pending > 0 && ' · '}{pending > 0 && `${pending} ${tx(lang,'updates waiting to send')}`}</div>}
    {requestLink && phase === 'desk' && <div className="gc-overlay" onClick={()=>setRequestLink('')}><section className="gc-dialog" role="dialog" aria-modal="true" aria-label="Share order link" onClick={e=>e.stopPropagation()}><button className="gc-close" onClick={()=>setRequestLink('')} aria-label="Close">×</button><h2>{tx(lang,supplierSharing?'Invite customers':reminder?'Send reminder':'Share order link')}</h2><p>{supplierSharing?settings.name:linkPhone}</p><p>{supplierSharing?tx(lang,'Share this public link with new customers.'):tx(lang,'Customer can tap the can to order.')}</p><input aria-label="Customer order link" readOnly value={requestLink}/><div className="delivery-share-actions"><button className="gc-primary" onClick={()=>void navigator.clipboard.writeText(requestLink).then(()=>setNotice('Link copied.')).catch(()=>setError('Select the link and copy it.'))}><Copy size={18}/>Copy</button><a className="gc-primary" href={`https://wa.me/${linkPhone?'91'+linkPhone:''}?text=${encodeURIComponent(supplierSharing?`Join ${settings.name}: ${requestLink}`:reminder?`Hi ${linkCustomer?.name??''}, time for fresh water? Tap to order from ${settings.name}: ${requestLink}`:`Order water from ${settings.name}: ${requestLink}`)}`} target="_blank" rel="noopener noreferrer">WhatsApp</a><a href={requestLink} target="_blank" rel="noopener noreferrer">Open order page</a>{linkCustomer&&!supplierSharing&&<button className="gc-quiet" disabled={busy||!!offlineSince} onClick={()=>void resetLink()}><Link2 size={17}/>{tx(lang,'New link')}</button>}</div></section></div>}
    {phase === 'loading' && <section className="gc-startup" aria-busy="true" aria-label="Opening delivery desk"><div className="gc-startup-heading"><h1>{tx(lang,'Today')}</h1><span>{tx(lang,'Opening your desk…')}</span></div><div className="home-hero home-hero-loading"><div className="home-order"><span className="home-order-icon"><Plus size={30}/></span><span className="home-order-text"><strong>{tx(lang,'Take a new order')}</strong></span></div></div><div className="gc-startup-placeholder"/></section>}
    {(phase === 'phone' || phase === 'code') && <section className="gc-login"><img className="gc-login-can" src="/icon-192.png" width="72" height="72" alt="GetCan watercan"/><h1>{phase === 'phone' ? 'Supplier login' : 'Enter OTP'}</h1>{phase === 'code' && <p>Sent to {phone}</p>}{phase === 'phone' ? <><label>Mobile number<input inputMode="tel" autoComplete="tel" placeholder="10-digit mobile number" value={phone} onChange={e => setPhone(e.target.value)} /></label><div ref={turnstileRef} className="gc-turnstile"/><button className="gc-primary" disabled={busy || !turnstileToken} onClick={sendCode}>Continue <ArrowRight size={18}/></button></> : <><label>Verification code<input inputMode="numeric" autoComplete="one-time-code" placeholder="Enter code" value={code} onChange={e => setCode(e.target.value)} /></label><button className="gc-primary" disabled={busy} onClick={verify}>Verify and continue <ArrowRight size={18}/></button><button className="gc-quiet" onClick={() => setPhase('phone')}>Change number</button></>}</section>}
    {phase === 'setup' && <section className="gc-login gc-setup">
      <div className="setup-top"><div className="setup-steps" aria-label={`${tx(lang,'Step')} ${setupStep === 'name' ? 1 : setupStep === 'price' ? 2 : 3} / 3`}>{(['name','price','install'] as const).map((step, i) => <span key={step} className={i <= ['name','price','install'].indexOf(setupStep) ? 'on' : ''}/>)}</div><LanguageSelect label={tx(lang,'Language')} value={lang} onChange={chooseLanguage}/></div>
      {setupStep === 'name' && <form onSubmit={e => { e.preventDefault(); nameNext(); }}><div className="setup-icon"><Store size={32}/></div><span className="gc-eyebrow">{tx(lang,'Welcome to GetCan')}</span><h1>{tx(lang,'What is your business name?')}</h1><p>{tx(lang,'Customers see this name on their order page.')}</p><label>{tx(lang,'Business name')}<input autoFocus maxLength={80} autoComplete="organization" placeholder="Sri Murugan Water" value={setupName} onChange={e => setSetupName(e.target.value)}/></label><button className="gc-primary" type="submit">{tx(lang,'Next')} <ArrowRight size={18}/></button></form>}
      {setupStep === 'price' && <form onSubmit={e => { e.preventDefault(); void saveSetup(); }}><div className="setup-icon"><IndianRupee size={32}/></div><span className="gc-eyebrow">{setupName}</span><h1>{tx(lang,'What is your price for one water can?')}</h1><p>{tx(lang,'New orders use this price. You can change it later in Settings.')}</p><label>{tx(lang,'Price per can (₹)')}<span className="setup-price"><span>₹</span><input autoFocus inputMode="decimal" type="number" min="1" max="1000" step="0.5" placeholder="35" value={setupPrice} onChange={e => setSetupPrice(e.target.value)}/></span></label><button className="gc-primary" type="submit" disabled={busy}>{tx(lang,'Save and continue')} <ArrowRight size={18}/></button><button type="button" className="gc-quiet" onClick={() => { setError(''); setSetupStep('name'); }}>{tx(lang,'Back')}</button></form>}
      {setupStep === 'install' && <div><img className="setup-app-icon" src="/icon-192.png" width="84" height="84" alt=""/><span className="gc-eyebrow">{tx(lang,'Almost done')}</span><h1>{tx(lang,'Add GetCan to your home screen')}</h1><p>{tx(lang,'Open it in one tap, like any other app.')}</p>{installHelp && <p className="setup-help">{tx(lang, installer.ios ? 'In Safari, tap Share, then Add to Home Screen.' : 'Open the browser menu (⋮) and choose Install app or Add to Home screen.')}</p>}<button className="gc-primary" onClick={() => void installFromSetup()}><Download size={18}/>{tx(lang,'Install app')}</button><button className="gc-quiet" onClick={() => void refresh()}>{tx(lang,'Skip for now')}</button></div>}
    </section>}
    {phase === 'billing' && <section className="gc-login"><div className="gc-icon"><Truck size={35}/></div><span className="gc-eyebrow">GETCAN FOR DISTRIBUTORS</span><h1>Run every delivery in one place.</h1><p>Customers, one-tap requests, delivery rhythm, payments and empty cans.</p><div className="gc-plan"><strong>₹50 <small>/ month</small></strong><span>₹50/month core plan</span></div>{billing?.checkoutUrl ? <a className="gc-primary" href={billing.checkoutUrl}>Complete subscription <ArrowRight size={18}/></a> : <button className="gc-primary" disabled={busy} onClick={subscribe}>Start subscription <ArrowRight size={18}/></button>}<button className="gc-quiet" onClick={() => void refresh()}><RefreshCw size={16}/> I have paid — refresh</button></section>}
    {phase === 'desk' && <div className="gc-desk"><div className="gc-title"><div><span className="gc-eyebrow">{settings.name || 'GETCAN'}</span><h1>{tx(lang,tab === 'today' ? 'Today' : tab === 'route' ? 'Delivery' : tab[0].toUpperCase() + tab.slice(1))}</h1></div><div className="gc-title-actions"><LanguageSelect label={tx(lang,'Language')} value={lang} onChange={chooseLanguage}/>{pushKey && pushSupported() && <button className="gc-quiet gc-icon-button" disabled={busy || alertsOn} onClick={() => void turnOnAlerts()} aria-label={tx(lang, alertsOn ? 'Alerts on' : 'Turn on alerts')} title={tx(lang, alertsOn ? 'Alerts on' : 'Turn on alerts')}>{alertsOn ? <BellRing size={19}/> : <Bell size={19}/>}</button>}<button className="gc-quiet gc-icon-button" onClick={() => setShowSettings(true)} aria-label={tx(lang,'Settings')}><Settings2 size={19}/></button>{tab !== 'today' && <button className="gc-primary gc-new-order" onClick={() => openQuick()}><Plus size={20}/>{tx(lang,'New order')}</button>}</div></div><nav className="gc-tabs" aria-label="Distributor sections">{([['today','Today'],['orders','Orders'],['customers','Customers'],['route','Delivery'],['ledger','Ledger']] as const).map(([id,label]) => <button key={id} aria-current={tab === id ? 'page' : undefined} className={tab === id ? 'active' : ''} onClick={() => { setTab(id); window.scrollTo({top:0,behavior:'instant'}); }}>{id === 'today' ? <Home size={23}/> : id === 'orders' ? <ClipboardList size={23}/> : id === 'customers' ? <Users size={23}/> : id === 'route' ? <Truck size={23}/> : <Wallet size={23}/>}<span>{tx(lang,label)}</span></button>)}</nav>
      {tab === 'today' && <><section className="home-hero"><div className="home-hero-copy"><small>{new Date().toLocaleDateString(locale(lang),{weekday:'long',day:'numeric',month:'long'})}</small><h2>{tx(lang,greeting())}</h2></div><button className="home-order" onClick={() => openQuick()}><span className="home-order-icon"><Plus size={34}/></span><span className="home-order-text"><strong>{tx(lang,'Take a new order')}</strong><small>{tx(lang,'Search a customer or add one in the same step')}</small></span><ArrowRight className="home-order-arrow" size={24}/></button></section><div className="gc-columns"><section className="gc-panel"><h2>{tx(lang,'New requests')} <span className="head-count">{newOrders.length}</span></h2><div className="gc-list">{newOrders.slice(0,5).map(o => <div key={o.id} className="gc-order"><span><strong>{o.customer}</strong><small>{o.quantity} cans · ₹{(o.quantity * o.price_cents / 100).toFixed(0)}</small></span><button disabled={busy} onClick={() => advance(o)}>{tx(lang,'Out for delivery')}</button></div>)}{!newOrders.length && <p className="gc-empty">{tx(lang,'No new requests.')}</p>}</div></section><section className="gc-panel"><h2>{tx(lang,'May need water soon')} <span className="head-count">{dueThisWeek.length}</span></h2><div className="gc-list">{dueThisWeek.slice(0,5).map(c => <div key={c.id} className="gc-person"><span className="gc-avatar"><Droplets size={18}/></span><span><strong>{c.name}</strong><small>{c.usual_quantity} usual cans · every {c.frequency_days} days</small></span><div className="gc-customer-actions"><button disabled={busy || !!offlineSince} onClick={() => void shareCustomer(c, true)}><MessageCircle size={15}/> {tx(lang,'Remind')}</button><button onClick={() => openQuick('order', c.phone)}><Plus size={15}/> {tx(lang,'Order')}</button></div></div>)}{!dueThisWeek.length && <p className="gc-empty">{tx(lang,'No customers predicted this week yet.')}</p>}</div></section></div></>}
      {tab === 'orders' && <section className="gc-panel"><div className="gc-panel-head"><h2>{tx(lang,'All orders')}</h2><button className="gc-quiet" onClick={() => openQuick()}><Plus size={17}/>{tx(lang,'New order')}</button></div><button className="order-search-launch" onClick={() => openQuick()}><Search size={22}/><span><strong>{tx(lang,'Take a new order')}</strong><small>{tx(lang,'Search by name or mobile. New customers are added while ordering.')}</small></span><Plus size={21}/></button><div className="gc-list">{orders.map(o => <div key={o.id} className="gc-order"><span><strong>{o.customer}</strong><small>#{o.id} · {o.quantity} cans · ₹{(o.quantity * o.price_cents / 100).toFixed(0)} · {o.status.replaceAll('_', ' ')}</small></span>{o.status !== 'delivered' && <button disabled={busy} onClick={() => advance(o)}>{tx(lang,o.status === 'out_for_delivery' ? 'Mark delivered' : 'Out for delivery')}</button>}</div>)}{!orders.length && <p className="gc-empty">Orders will appear here.</p>}</div></section>}
      {tab === 'customers' && <section className="gc-panel"><div className="gc-panel-head"><h2>{tx(lang,'Customers')}</h2><button className="gc-primary" onClick={() => openQuick('customer')}><Plus size={17}/>{tx(lang,'Add customer')}</button></div><div className="gc-customer-tools"><button onClick={()=>setShowImport(true)}>{tx(lang,'Import customers')}</button><button disabled={busy} onClick={()=>void shareSupplier()}>{tx(lang,'Invite customers')}</button></div><input placeholder={tx(lang,"Search name or phone")} aria-label="Search customers" value={search} onChange={e => setSearch(e.target.value)}/><div className="gc-list">{customers.filter(c => `${c.name} ${c.phone} ${c.area} ${c.address}`.toLowerCase().includes(search.toLowerCase())).map(c => <div key={c.id} className="gc-person"><span className="gc-avatar">{c.name[0]?.toUpperCase()}</span><span><strong>{c.name}</strong><small>{c.phone} · {c.area || tx(lang,'No area added')} · {c.usual_quantity} {tx(lang,'cans')}</small></span><div className="gc-customer-actions"><button disabled={busy} onClick={() => void shareCustomer(c)}>{tx(lang,'Share order link')}</button><button onClick={() => editCustomer(c)}>{tx(lang,'Edit')}</button><button onClick={() => openQuick('order',c.phone)}>{tx(lang,'Order')}</button></div></div>)}{!customers.length && <p className="gc-empty">Add a number to start your customer book.</p>}</div></section>}
      {tab === 'route' && <section className="gc-panel"><div className="gc-panel-head"><h2>{tx(lang,'Delivery')}</h2><span>{openOrders.length} {tx(lang,'Open')}</span></div><label className="delivery-search"><Search size={20}/><input placeholder={tx(lang,'Search name, mobile or area')} aria-label={tx(lang,'Search name, mobile or area')} value={deliverySearch} onChange={e=>setDeliverySearch(e.target.value)}/></label><div className="delivery-area-filters"><button className={deliveryArea===null?'active':''} onClick={()=>setDeliveryArea(null)}>{tx(lang,'All')}</button>{areas.map(area=><button key={area} className={deliveryArea===area?'active':''} onClick={()=>setDeliveryArea(area)}>{openOrders.find(o=>areaKey(o.area)===area)?.area || tx(lang,'No area added')} · {openOrders.filter(o=>areaKey(o.area)===area).length}</button>)}</div>{areas.filter(area=>visibleDeliveries.some(o=>areaKey(o.area)===area)).map(area=>{const group=visibleDeliveries.filter(o=>areaKey(o.area)===area);const ready=openOrders.filter(o=>areaKey(o.area)===area&&o.status!=='out_for_delivery');return <section key={area} className="delivery-area"><div className="gc-panel-head"><div><h3>{group[0].area || tx(lang,'No area added')}</h3><small>{group.length} {tx(lang,'Orders')} · {group.reduce((n,o)=>n+o.quantity,0)} {tx(lang,'cans')}</small></div>{ready.length>0&&<button className="gc-primary" disabled={busy} onClick={()=>void startArea(area)}><Truck size={17}/>{tx(lang,'Out for delivery')} · {ready.length}</button>}</div><div className="gc-list">{group.map(o=><div key={o.id} className="delivery-customer"><div className="delivery-person"><strong>{o.customer}</strong><small>{o.phone} · {o.area || tx(lang,'No area added')}</small><small>{o.address}</small><span className={o.status==='out_for_delivery'?'delivery-status onway':'delivery-status'}>{tx(lang,o.status==='out_for_delivery'?'Out for delivery':'Ready to dispatch')}</span></div><div className="delivery-total"><strong>{o.quantity} {tx(lang,'cans')}</strong><small>₹{(o.quantity*o.price_cents/100).toLocaleString('en-IN')}</small></div><div className="delivery-actions"><a href={`tel:${o.phone}`} aria-label={`${tx(lang,'Call')} ${o.customer}`}><Phone size={18}/>{tx(lang,'Call')}</a><button disabled={busy} className="gc-primary" onClick={()=>finish(o)}><Check size={18}/>{tx(lang,'Mark delivered')}</button></div></div>)}</div></section>})}{!visibleDeliveries.length&&<p className="gc-empty">{tx(lang,'No orders here')}</p>}</section>}
      {tab === 'ledger' && <section className="gc-panel"><h2>{tx(lang,'Customer balances')}</h2>{summary&&<><p className="gc-summary-date">{tx(lang,'Today')} · {new Date(summary.day+'T12:00:00+05:30').toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</p><div className="gc-daily-summary">{[['Sales today',`₹${(summary.sales_cents/100).toLocaleString('en-IN')}`],['Collected today',`₹${(summary.collected_cents/100).toLocaleString('en-IN')}`],['Cans delivered',summary.delivered_cans],['Empties collected',summary.returned_cans],['Total dues',`₹${(summary.dues_cents/100).toLocaleString('en-IN')}`],['Cans with customers',summary.cans_out]].map(([label,value])=><div key={label}><small>{tx(lang,String(label))}</small><strong>{value}</strong></div>)}</div><small>{tx(lang,'Dues and cans with customers include full history.')}{summary.credit_cents>0&&` · Customer credit ₹${(summary.credit_cents/100).toLocaleString('en-IN')}`}</small></>}<div className="gc-list">{customers.map(c => <div key={c.id} className="gc-order"><span><strong>{c.name}</strong><small>{cansOut(c)} empty cans out</small></span><div><strong>{balance(c)<0?tx(lang,'Credit'):tx(lang,'Due')} ₹{(Math.abs(balance(c))/100).toFixed(0)}</strong><button onClick={() => setStatementCustomer(c)}><FileText size={15}/> {tx(lang,'Statement')}</button><button onClick={() => { setPaymentCustomer(c); setMethod('cash'); setPaid(String(Math.max(0,balance(c))/100)); }}>{tx(lang,'Payment')}</button><button disabled={busy||cansOut(c)<=0} onClick={()=>openCollection(c)}>{tx(lang,'Collect empty cans')}</button></div></div>)}{!customers.length && <p className="gc-empty">Balances appear after adding customers.</p>}</div></section>}
    <footer className="gc-plan-footer">{billing?.trialEnd && <span>Free access until {new Date(billing.trialEnd).toLocaleDateString('en-IN',{day:'numeric',month:'short'})} · then ₹50/month</span>}</footer>
    </div>}
    {showImport&&phase==='desk'&&<CustomerImport onClose={()=>setShowImport(false)} onDone={async message=>{setNotice(message);await refresh();}}/>}
    {collectionCustomer&&phase==='desk'&&<div className="gc-overlay" onClick={()=>setCollectionCustomer(null)}><section className="gc-dialog" role="dialog" aria-modal="true" aria-label="Collect empty cans" onClick={e=>e.stopPropagation()}><button className="gc-close" aria-label="Close" onClick={()=>setCollectionCustomer(null)}>×</button><h2>{tx(lang,'Collect empty cans')}</h2><p>{collectionCustomer.name} · {cansOut(collectionCustomer)} {tx(lang,'Cans with customers')}</p><label>{tx(lang,'Empty cans collected')}<div className="gc-stepper"><button disabled={collectionCount<=1} onClick={()=>setCollectionCount(n=>n-1)} aria-label="One fewer can"><Minus/></button><input aria-label="Number of empty cans" type="number" min="1" max={cansOut(collectionCustomer)} value={collectionCount} onChange={e=>setCollectionCount(Number(e.target.value))}/><button disabled={collectionCount>=cansOut(collectionCustomer)} onClick={()=>setCollectionCount(n=>n+1)} aria-label="One more can"><Plus/></button></div></label>{error&&<p className="quick-error" role="alert">{error}</p>}<button className="gc-primary" disabled={busy||!Number.isInteger(collectionCount)||collectionCount<1||collectionCount>cansOut(collectionCustomer)} onClick={()=>void collectCans()}>{tx(lang,'Save collection')} <Check size={19}/></button></section></div>}
    {statementCustomer && phase === 'desk' && <Statement customer={statementCustomer} lang={lang} onClose={() => setStatementCustomer(null)}/>}
    {showSettings && phase === 'desk' && <div className="gc-overlay" onClick={() => setShowSettings(false)}><section className="gc-dialog" role="dialog" aria-modal="true" aria-label="Distributor settings" onClick={e => e.stopPropagation()}><button className="gc-close" aria-label="Close" onClick={() => setShowSettings(false)}>×</button><h2>{tx(lang,'Settings')}</h2><label>{tx(lang,'Business name')}<input value={settings.name} onChange={e => setSettings({ ...settings, name: e.target.value })}/></label><label>{tx(lang,'Price per can (₹)')}<input type="number" min="0" step="0.01" value={settings.default_price_cents / 100} onChange={e => setSettings({ ...settings, default_price_cents: Math.round(Number(e.target.value) * 100) })}/></label><p>One price applies to new orders. Existing orders keep their saved price.</p><label>{tx(lang,'UPI ID for customer payments')}<input placeholder="yourname@okbank" autoCapitalize="none" value={settings.upi_id} onChange={e => setSettings({ ...settings, upi_id: e.target.value })}/></label><p>Customers with dues see a Pay by UPI button, a QR code and your UPI ID on their order page. Use a business UPI ID (Google Pay for Business, PhonePe Business, Paytm for Business or BharatPe) so the button works in every app. Google Pay often blocks the button for personal UPI IDs with a bank limit error; customers can still scan the QR code or copy the ID.</p><button className="gc-primary" disabled={busy} onClick={saveSettings}>{tx(lang,'Save settings')}</button><div className="settings-more"><InstallApp/><button className="gc-quiet settings-signout" onClick={() => void logout()}><LogOut size={16}/>{tx(lang,'Sign out')}</button></div></section></div>}
    {editingCustomer && phase === 'desk' && <div className="gc-overlay" onClick={() => setEditingCustomer(null)}><section className="gc-dialog" role="dialog" aria-modal="true" aria-label="Edit customer" onClick={e => e.stopPropagation()}><button className="gc-close" onClick={() => setEditingCustomer(null)}>×</button><h2>{tx(lang,'Edit customer')}</h2><label>{tx(lang,'Name')}<input value={customerDraft.name} onChange={e => setCustomerDraft({ ...customerDraft, name: e.target.value })}/></label><label>{tx(lang,'Mobile')}<input inputMode="tel" value={customerDraft.phone} onChange={e => setCustomerDraft({ ...customerDraft, phone: e.target.value })}/></label><label>{tx(lang,'Area')}<input value={customerDraft.area} onChange={e=>setCustomerDraft({...customerDraft,area:e.target.value})}/></label><label>{tx(lang,'Address')}<input value={customerDraft.address} onChange={e => setCustomerDraft({ ...customerDraft, address: e.target.value })}/></label><label>{tx(lang,'Usual cans')}<input type="number" min="1" max="50" value={customerDraft.usualQuantity} onChange={e => setCustomerDraft({ ...customerDraft, usualQuantity: Number(e.target.value) })}/></label><label>{tx(lang,'Days between deliveries')}<input type="number" min="1" max="90" value={customerDraft.frequencyDays} onChange={e => setCustomerDraft({ ...customerDraft, frequencyDays: Number(e.target.value) })}/></label><button className="gc-primary" disabled={busy} onClick={saveCustomerEdit}>{tx(lang,'Save customer')}</button></section></div>}
    {paymentCustomer && phase === 'desk' && <div className="gc-overlay" onClick={() => setPaymentCustomer(null)}><section className="gc-dialog" role="dialog" aria-modal="true" aria-label="Record payment" onClick={e => e.stopPropagation()}><button className="gc-close" onClick={() => setPaymentCustomer(null)}>×</button><h2>Payment from {paymentCustomer.name}</h2><p>Balance ₹{(balance(paymentCustomer)/100).toFixed(0)}</p><label>{method === 'upi' ? 'UPI received (₹)' : 'Cash received (₹)'}<input type="number" min="0.01" step="0.01" value={paid} onChange={e => setPaid(e.target.value)}/></label>{methodPicker}<button className="gc-primary" disabled={busy} onClick={recordPayment}>Record payment</button></section></div>}
    {quickMode && phase === 'desk' && <QuickOrder key={`${quickMode}-${quickPhone}`} endpoint={quickMode === 'order' ? '/api/commercial/quick-order' : '/api/commercial/customers'} lookupEndpoint="/api/commercial/quick-order" people={customers} priceCents={settings.default_price_cents} initialPhone={quickPhone} lang={lang} saveOnly={quickMode === 'customer'} onClose={() => setQuickMode(null)} onDone={quickDone}/>}
    {selectedDelivery && phase === 'desk' && <div className="gc-overlay" onClick={() => setSelectedDelivery(null)}><section className="gc-dialog" role="dialog" aria-modal="true" aria-label="Complete delivery" onClick={e => e.stopPropagation()}><button className="gc-close" onClick={() => setSelectedDelivery(null)}>×</button><span className="gc-eyebrow">COMPLETE DELIVERY</span><h2>{selectedDelivery.customer}</h2><p>{selectedDelivery.quantity} cans · ₹{(selectedDelivery.quantity * selectedDelivery.price_cents / 100).toFixed(0)} total</p><label>{tx(lang,'Empty cans collected')}<div className="gc-stepper"><button disabled={returned <= 0} onClick={() => setReturned(n => n - 1)} aria-label="One fewer empty can"><Minus/></button><strong>{returned}</strong><button disabled={returned >= Math.min(100,(accounts.find(c=>c.customer_id===selectedDelivery.customer_id)?.cans_out??0) + selectedDelivery.quantity)} onClick={() => setReturned(n => n + 1)} aria-label="One more empty can"><Plus/></button></div></label><label>{tx(lang,'Cash received (₹)')}<input inputMode="decimal" type="number" min="0" step="0.01" value={paid} onChange={e => setPaid(e.target.value)}/></label>{methodPicker}<button className="gc-primary" disabled={busy} onClick={completeDelivery}>{tx(lang,'Mark delivered')} <Check size={19}/></button></section></div>}
  </main>;
}
